<?php
if (!defined('IN_CONTEXT')) die('access violation error!');
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n";
echo "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head>\n";
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n";
echo "<title>企业网站后台管理系统</title>\n";
echo "<style type=\"text/css\"> \n";
echo "html{ overflow:hidden;}\n";
echo "table,td,th, body,dt,dd,dl{ margin:0; padding:0; border:none;}\n";
echo "#nav { background: repeat-x url(images/master/repeat.gif) 0 -209px ; font-size:12px; \n";
echo "position:static; top:0; left:0;height:32px; line-height:26px; padding: 0 10px; }\n";
echo "#nav a { color:#666; text-decoration:none; }\n";
echo "#nav a:hover { color:#f60; text-decoration:underline;}\n";
echo "#nav dt, #nav dd { float:left;}\n";
echo "#nav dd { color:#999;}\n";
echo "#nav dt,#nav dd.link {padding-right:16px; background:url(images/master/images.gif) \n";
echo "no-repeat right -204px;}\n";
echo "</style>\n";
echo "</head>\n";
echo "<body scroll=\"no\">\n";
echo "<table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" height=\"100%\">\n";
echo "    <tr>\n";
echo "        <td colspan=\"2\" height=\"95\"><iframe src=\"header.php\" name=\"header\" target=\"menu\" \n";
echo "width=\"100%\" height=\"95\" scrolling=\"no\" frameborder=\"0\"></iframe></td>\n";
echo "    </tr>\n";
echo "    <tr>\n";
echo "        <td valign=\"top\" rowspan=\"2\" width=\"137\"><iframe src=\"menu.php\" name=\"menu\" \n";
echo "target=\"main\" width=\"138\" height=\"100%\" scrolling=\"no\" frameborder=\"0\"></iframe></td>\n";
echo "        <td valign=\"top\" height=\"100%\">\n";
echo "        \n";
echo "        \n";
echo "        	<table  cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" height=\"100%\">\n";
echo "                <tr>\n";
echo "                    <td valign=\"top\" width=\"100%\"><iframe src=\"main.php\" id=\"main\" \n";
echo "name=\"main\" width=\"100%\" height=\"100%\" frameborder=\"0\" scrolling=\"yes\" \n";
echo "style=\"overflow:visible;\"></iframe></td>\n";
echo "                </tr>\n";
echo "            </table>\n";
echo "        \n";
echo "        </td>\n";
echo "    </tr>\n";
echo "</table> \n";
echo "</body>\n";
echo "</html>\n";
?>